<a href="https://colab.research.google.com/github/Rozieyati/Data-Science-Project/blob/main/P166417_Project_1_STQD6014_Data_Science.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#PART 2 - LISTS, DICTIONARIES AND LOOPING

In [ ]:
#5 Cities I want to visit.

cities = {
    "Istanbul" : {
        "country" : "Turkey",
        "population" : 15.5,
        "landmarks" : ["Hagia Sophia", "Blue Mosque", "Topkapi Palace"],
        "dishes" : ["Kebab", "Baklava", "Menemen"]
    },

    "Makkah" : {
        "country" : "Saudi Arabia",
        "population" : 2.0,
        "landmarks" : ["Masjid Al-Haram", "Kaabah", "Hajarul Aswad"],
        "dishes" : ["Kabsa", "Mandy", "Mutabbaq"]
    },

     "Sydney" : {
        "country" : "Australia",
        "population" : 5.3,
        "landmarks" : ["Sydney Opera House", "Harbour Bridge", "Bondi Beach"],
        "dishes" : ["Meat Pie", "Fish and Chips", "Lamington"]
    },

     "Jakarta" : {
        "country" : "Indonesia",
        "population" : 10.7,
        "landmarks" : ["Monas Tower", "Istiqlal Mosque", "Kota Tua"],
        "dishes" : ["Bakso", "Gado-Gado", "Nasi Padang"]
    },

     "Bangkok" : {
        "country" : "Thailand",
        "population" : 11.0,
        "landmarks" : ["Grand Palace", "Wat Arun", "Chatuchak Market"],
        "dishes" : ["Pad Thai", "Tom Yum", "Mango Sticky Rice"]
    }
}
for city, info in cities.items():
    print(f"City: {city}")
    print(f"Country: {info['country']}")
    print(f"Population: {info['population']} million")

    print("Landmarks:")
    for landmark in info['landmarks']:
        print(f" - {landmark}")


    print("Local Dishes:")
    for dish in info['dishes']:
        print(f" - {dish}")

    print()

City: Istanbul
Country: Turkey
Population: 15.5 million
Landmarks:
 - Hagia Sophia
 - Blue Mosque
 - Topkapi Palace
Local Dishes:
 - Kebab
 - Baklava
 - Menemen

City: Makkah
Country: Saudi Arabia
Population: 2.0 million
Landmarks:
 - Masjid Al-Haram
 - Kaabah
 - Hajarul Aswad
Local Dishes:
 - Kabsa
 - Mandy
 - Mutabbaq

City: Sydney
Country: Australia
Population: 5.3 million
Landmarks:
 - Sydney Opera House
 - Harbour Bridge
 - Bondi Beach
Local Dishes:
 - Meat Pie
 - Fish and Chips
 - Lamington

City: Jakarta
Country: Indonesia
Population: 10.7 million
Landmarks:
 - Monas Tower
 - Istiqlal Mosque
 - Kota Tua
Local Dishes:
 - Bakso
 - Gado-Gado
 - Nasi Padang

City: Bangkok
Country: Thailand
Population: 11.0 million
Landmarks:
 - Grand Palace
 - Wat Arun
 - Chatuchak Market
Local Dishes:
 - Pad Thai
 - Tom Yum
 - Mango Sticky Rice



In [ ]:
#PART 3 - FUNCTIONS AND CLASSES

In [ ]:
#3.2 Class, function and inheritance

# Parent class untuk penerima bantuan individu/isi rumah
class PenerimaBantuanIndividu_IsiRumah:
    def __init__(self, nama, umur, lokasi, negeri, nama_program, kategori_bantuan, jenis_bantuan):
        self.nama = nama
        self.umur = umur
        self.lokasi = lokasi
        self.negeri = negeri
        self.nama_program = nama_program
        self.kategori_bantuan = kategori_bantuan
        self.jenis_bantuan = jenis_bantuan

    def display_info(self):
        print(f"Nama                       : {self.nama}")
        print(f"Umur                       : {self.umur} tahun")
        print(f"Lokasi                     : {self.lokasi}")
        print(f"Negeri                     : {self.negeri}")
        print(f"Nama Program               : {self.nama_program}")
        print(f"Kategori Bantuan           : {self.kategori_bantuan}")
        print(f"Jenis Bantuan              : {self.jenis_bantuan}")
        print("-" * 50)


# Child class untuk penerima bantuan komuniti/kumpulan
class PenerimaBantuanKomuniti:
    def __init__(self, nama_komuniti, lokasi, negeri, nama_program, kategori_bantuan,
                 jenis_bantuan, jumlah_ahli_komuniti, kategori_komuniti):
        self.nama_komuniti = nama_komuniti
        self.lokasi = lokasi
        self.negeri = negeri
        self.nama_program = nama_program
        self.kategori_bantuan = kategori_bantuan
        self.jenis_bantuan = jenis_bantuan
        self.jumlah_ahli_komuniti = jumlah_ahli_komuniti
        self.kategori_komuniti = kategori_komuniti

    def display_info(self):
        print(f"Komuniti                   : {self.nama_komuniti}")
        print(f"Lokasi                     : {self.lokasi}")
        print(f"Negeri                     : {self.negeri}")
        print(f"Nama Program               : {self.nama_program}")
        print(f"Kategori Bantuan           : {self.kategori_bantuan}")
        print(f"Jenis Bantuan              : {self.jenis_bantuan}")
        print(f"Jumlah Ahli Komuniti       : {self.jumlah_ahli_komuniti}")
        print(f"Kategori Komuniti          : {self.kategori_komuniti}")
        print("-" * 50)




In [ ]:
#3.3 Test 5 instances of each parent and child class

#5 instances of Parent_Penerima bantuan individu/isi rumah

penerima1 = PenerimaBantuanIndividu_IsiRumah(
    "Shafiq", 45, "Tanah Merah", "Kelantan",
    "Program Kemahiran Keusahawanan",
    "Livelihood", "Latihan Asas Keusahawanan & Bantuan Peralatan: Freezer")

penerima2 = PenerimaBantuanIndividu_IsiRumah(
    "Zabidah", 65, "Sik", "Kedah",
    "Program Sumbangan Bakul Makanan",
    "One-Off", "Set Bakul Makanan")

penerima3 = PenerimaBantuanIndividu_IsiRumah(
    "Kamal", 38, "Kapar", "Selangor",
    "Program Latihan Kemahiran Usahawan",
    "Livelihood", "Latihan Asas Keusahawanan & Bantuan Peralatan: Air Compressor Paint")

penerima4 = PenerimaBantuanIndividu_IsiRumah(
    "Jamal", 70, "Sungai Pinang", "Kelantan",
    "Program Sumbangan Bakul Makanan",
    "One-Off", "Set Bakul Makanan")

penerima5 = PenerimaBantuanIndividu_IsiRumah(
    "Rapita", 29, "Matunggong", "Sabah",
    "Program Latihan Kemahiran Usahawan",
    "Livelihood", "Latihan Asas Keusahawanan & Bantuan Peralatan: Portable Massage Bed")

print("===== Penerima Bantuan Individu / Isi Rumah =====")
for penerima in [penerima1, penerima2, penerima3, penerima4, penerima5]:
    penerima.display_info()

===== Penerima Bantuan Individu / Isi Rumah =====
Nama                       : Shafiq
Umur                       : 45 tahun
Lokasi                     : Tanah Merah
Negeri                     : Kelantan
Nama Program               : Program Kemahiran Keusahawanan
Kategori Bantuan           : Livelihood
Jenis Bantuan              : Latihan Asas Keusahawanan & Bantuan Peralatan: Freezer
--------------------------------------------------
Nama                       : Zabidah
Umur                       : 65 tahun
Lokasi                     : Sik
Negeri                     : Kedah
Nama Program               : Program Sumbangan Bakul Makanan
Kategori Bantuan           : One-Off
Jenis Bantuan              : Set Bakul Makanan
--------------------------------------------------
Nama                       : Kamal
Umur                       : 38 tahun
Lokasi                     : Kapar
Negeri                     : Selangor
Nama Program               : Program Latihan Kemahiran Usahawan
Kategori Bant

In [ ]:
#3.3 Test 5 instances of each parent and child class

#5 instances of child class_Penerima bantuan komuniti/kumpulan

komuniti1 = PenerimaBantuanKomuniti(
    "Kg. Suang Punggor", "Kota Belud", "Sabah","Program Keusahawanan Pembangunan Komuniti",
    "Livelihood", "Latihan Asas Keusahawanan & Set Fertigasi Cili", 50, "Pedalaman")

komuniti2 = PenerimaBantuanKomuniti(
    "PPR Seri Semarak", "Kuala Lumpur", "Wilayah Persekutuan",
    "Program Melestarikan Pusat Tuisyen Blok D", "Livelihood",
    "Set Kelengkapan Pusat Tuisyen", 100, "B40")

komuniti3 = PenerimaBantuanKomuniti(
    "Kg. Pelanduk", "Sik", "Kedah",
    "Program Penternakan Madu Kelulut", "Livelihood",
    "Set Kelengkapan Log Kelulut", 20, "Asnaf")

komuniti4 = PenerimaBantuanKomuniti(
    "PPR Sungai Bonus", "Kuala Lumpur", "Wilayah Persekutuan",
    "Program Hari Belia & Sukan", "One-Off",
    "Set Kelengkapan Gelanggang Bola Tampar", 35, "Bandar")

komuniti5 = PenerimaBantuanKomuniti(
    "Tingkatan 5, SK.Pulau Indah", "Pulau Indah", "Selangor",
    "Bantuan Device untuk Mode Pembelajaran dari Rumah", "One-Off",
    "Laptop", 100, "Pelajar Sekolah Menengah")

print("===== Penerima Bantuan Komuniti / Kumpulan =====")
for komuniti in [komuniti1, komuniti2, komuniti3, komuniti4, komuniti5]:
    komuniti.display_info()

===== Penerima Bantuan Komuniti / Kumpulan =====
Komuniti                   : Kg. Suang Punggor
Lokasi                     : Kota Belud
Negeri                     : Sabah
Nama Program               : Program Keusahawanan Pembangunan Komuniti
Kategori Bantuan           : Livelihood
Jenis Bantuan              : Latihan Asas Keusahawanan & Set Fertigasi Cili
Jumlah Ahli Komuniti       : 50
Kategori Komuniti          : Pedalaman
--------------------------------------------------
Komuniti                   : PPR Seri Semarak
Lokasi                     : Kuala Lumpur
Negeri                     : Wilayah Persekutuan
Nama Program               : Program Melestarikan Pusat Tuisyen Blok D
Kategori Bantuan           : Livelihood
Jenis Bantuan              : Set Kelengkapan Pusat Tuisyen
Jumlah Ahli Komuniti       : 100
Kategori Komuniti          : B40
--------------------------------------------------
Komuniti                   : Kg. Pelanduk
Lokasi                     : Sik
Negeri               

In [ ]:
# PART 4 - FILES AND EXCEPTIONS

# 4.1.a) Creates two files, movie.txt and sport.txt and stores at least five names of movies and sports line by line

#Initial file creation and reading

import os

# Define filenames
movie_filename = 'movie.txt'
sport_filename = 'sport.txt'
missing_filename = 'non_existent_file.txt'

print("--- FILE SETUP ---")

# Create to movie.txt
movie_data = ["Agak Laen\n","Seruan Syaitan\n","Mr. Bean\n","My Destiny\n","3 Idiots\n"]

with open(movie_filename, 'w') as f_movie:
    f_movie.writelines(movie_data)

print(f"1. Successfully created '{movie_filename}'.")

# Create to sport.txt
sport_data = ["Netball\n","Basketball\n","Baseball\n","Tennis\n","Swimming\n"]

with open(sport_filename, 'w') as f_sport:
    f_sport.writelines(sport_data)

print(f"2. Successfully created '{sport_filename}'.")

# Read and print the contents of both files
print("\n --- INITIAL CONTENTS OF MOVIES & SPORTS ---")

# Read movie.txt using read
print(f"\nContents of {movie_filename}:")
with open(movie_filename) as file_object:
    contents = file_object.read()
    print(contents)

# Read sport.txt using a for loop
print(f"\nContents of {sport_filename}:")
with open(sport_filename) as file_object:
    for line in file_object:
        print(line.rstrip())

--- FILE SETUP ---
1. Successfully created 'movie.txt'.
2. Successfully created 'sport.txt'.

 --- INITIAL CONTENTS OF MOVIES & SPORTS ---

Contents of movie.txt:
Agak Laen
Seruan Syaitan
Mr. Bean
My Destiny
3 Idiots


Contents of sport.txt:
Netball
Basketball
Baseball
Tennis
Swimming


In [ ]:
#4.1.b) Add five newlines to both files with a suitable explanation.
# Movie_filename = 'movie.txt' and sport_filename = 'sport.txt' are defined

print("\n--- NEWLINES AND EXPLANATIONS ---")

# Content to append to movie.txt
movie_append = [
    "\n*** The genre of the movie: ***\n",
    "1. Agak Laen is a unique blend of dark comedy mixed with chilling horror elements.\n",
    "2. Seruan Syaitan is terrifying supernatural horror film focusing on true evil and demonic calls.\n",
    "3. Mr. Bean is a famous slapstick comedy series known for its physical humour and starring Rowan Atkinson.\n",
    "My Destiny is a captivating film centred on powerful romance, deep family drama, and destiny.\n",
    "3 Idiots is an inspiring social comedy that blends heartwarming drama with educational themes.\n"
]

# Append to movie.txt
# Open the file in append mode ('a')
with open(movie_filename, 'a') as file_object:
    for line in movie_append:
        file_object.write(line) # The write() function requires explicit \n for new lines.

print(f"5+ descriptive lines added to added to {movie_filename} using 'a' mode.")

# Content to append to sport.txt (5+ newlines and explanation)
sport_append_lines = [
    "\n*** The characteristic of sport ***\n",
    "Requires passing accuracy and strict positional discipline.\n",
    "Emphasizes vertical jump, speed, and dribbling skill.\n",
    "Demands high hand-eye coordination and strategic awareness.\n",
    "Requires exceptional agility and precise ball control.\n",
    "Excellent for cardiovascular fitness and total body strength.\n"
]

# Append to sport.txt
with open(sport_filename, 'a') as file_object:
    for line in sport_append_lines:
        file_object.write(line)

print(f"5+ descriptive lines added to {sport_filename} using 'a' mode.")


--- NEWLINES AND EXPLANATIONS ---
5+ descriptive lines added to added to movie.txt using 'a' mode.
5+ descriptive lines added to sport.txt using 'a' mode.


In [ ]:
#4.1.c) Wrap code in a try-except block to catch the FileNotFound error
#print a friendly message if a file is missing.
#Move one of the files to a different location, and the code in the except block executes properly.

# --- WRAPPING CODE IN TRY-EXCEPT FOR FileNotFoundError ---
print("\n---HANDLING FileNotFoundError ---")

# Define files to check
movie_filename = 'movie.txt'
sport_filename = 'sport.txt'

# This file does not exist, simulating a file that was moved or misspelled.
missing_filename = 'non_existent_file.txt'

# List of files to check, including one guaranteed to be missing
files_to_check = [movie_filename, sport_filename, missing_filename]

for filename in files_to_check:
    print(f"\nAttempting to read file: {filename}")

# C.1. The 'try' block
# Code that might raise an exception (like opening a file that doesn't exist) goes here.
    try:
        # Try to open the file for reading ('r' is default)
        with open(filename) as f_obj:
            # Read the contents if the file is found
            contents = f_obj.read()
            print("SUCCESS: File found and contents read.")
            # Print a snippet to confirm content
            print(f"First line: {contents.splitlines()[0]}")

# C.2. The 'except' block
# If the FileNotFoundError occurs during the 'try' block, the code jumps immediately to this block.
    except FileNotFoundError:

# Print a friendly message instead of crashing the program
        msg = f"FILE MISSING: Sorry, the file '{filename}' does not exist or was moved from its original location."
        print(msg)

print("\n--- PROGRAM FINISHED CHECKING FILES ---")

# Remember: To fully test the prompt, manually move 'sport.txt' to another location and re-run the final section (4.c).


---HANDLING FileNotFoundError ---

Attempting to read file: movie.txt
SUCCESS: File found and contents read.
First line: Agak Laen

Attempting to read file: sport.txt
SUCCESS: File found and contents read.
First line: Netball

Attempting to read file: non_existent_file.txt
FILE MISSING: Sorry, the file 'non_existent_file.txt' does not exist or was moved from its original location.

--- PROGRAM FINISHED CHECKING FILES ---


In [ ]:
# PART 5 – NUMPY

#Array creation (A to J)

import numpy as np

# Set a seed for reproducible random arrays
np.random.seed(42)

# --- 1D Arrays (Size 5) ---
A = np.random.rand(5)  # single 1d array (Vector)
B = np.random.rand(5)  # single 1d array (Vector)

# --- 3x3 Arrays ---
C = np.random.rand(3, 3)
D = np.random.rand(3, 3)

# --- 2x4 Arrays ---
E = np.random.rand(2, 4)
F = np.random.rand(2, 4)

# --- 4x2 Arrays ---
G = np.random.rand(4, 2)
H = np.random.rand(4, 2)

# --- 5x5 Arrays ---
I = np.random.rand(5, 5)
J = np.random.rand(5, 5)

print("--- 10 CREATED NUMPY ARRAYS (A to J) ---")
print(f"Array A (1D) Shape: {A.shape}")
print(f"Array C (3x3) Shape: {C.shape}")
print(f"Array E (2x4) Shape: {E.shape}")
print(f"Array G (4x2) Shape: {G.shape}")
print(f"Array I (5x5) Shape: {I.shape}")

# Display example arrays
print("\nExample Array E (2x4):\n", E)
print("\nExample Array G (4x2):\n", G)

--- 10 CREATED NUMPY ARRAYS (A to J) ---
Array A (1D) Shape: (5,)
Array C (3x3) Shape: (3, 3)
Array E (2x4) Shape: (2, 4)
Array G (4x2) Shape: (4, 2)
Array I (5x5) Shape: (5, 5)

Example Array E (2x4):
 [[0.59241457 0.04645041 0.60754485 0.17052412]
 [0.06505159 0.94888554 0.96563203 0.80839735]]

Example Array G (4x2):
 [[0.25877998 0.66252228]
 [0.31171108 0.52006802]
 [0.54671028 0.18485446]
 [0.96958463 0.77513282]]


In [ ]:
#5.1 Perform operation on a single array

print("\n\n--- 1. OPERATIONS ON SINGLE ARRAY (13 Functions) ---")

# 1. dtype (Attribute)
print(f"\n1. Data type of A: {A.dtype}\n")

# 2. T (Transpose)
print(f"2. Transpose of C (3x3, first row):\n{C.T[0]}\n")

# 3. np.sqrt (Universal Function)
print(f"\n3. Square root of D (first element): {np.sqrt(D[0, 0]):.4f}\n")

# 4. np.ceil (Universal Function)
print(f"4. D first element rounded up: {np.ceil(D[0, 0]):.0f}\n")

# 5. np.log (Universal Function)
print(f"5. Natural log of A (first 3 values): {np.log(A[:3])}\n")

# 6. sum (Statistical Method)
print(f"\n6. Sum of E along rows (axis=1): {E.sum(axis=1)}\n")

# 7. mean (Statistical Method)
print(f"7. Mean of all elements in F: {F.mean():.4f}\n")

# 8. cumsum (Array Method)
print(f"\n8. Cumulative sum of I along columns (first row):\n{I.cumsum(axis=0)[0]}\n")

# 9. std (Statistical Method)
print(f"9. Standard deviation of I: {I.std():.4f}\n")

# 10. argmin (Array Method)
print(f"10. Index of minimum value in I (flattened): {I.argmin()}\n")

# 11. sort (Array Method - modifying C)
C.sort(axis=0)
print(f"11. C sorted along columns (first column): {C[:, 0]}\n")

# 12. np.unique (Set Logic)
print(f"12. Unique elements in A (all unique as it is random): {np.unique(A)}\n")

# 13. flatten (Array Method)
print(f"13. G flattened (first 4 values): {G.flatten()[:4]}\n")



--- 1. OPERATIONS ON SINGLE ARRAY (13 Functions) ---

1. Data type of A: float64

2. Transpose of C (3x3, first row):
[0.02058449 0.21233911 0.30424224]


3. Square root of D (first element): 0.5397

4. D first element rounded up: 1

5. Natural log of A (first 3 values): [-0.98205636 -0.05054168 -0.31198304]


6. Sum of E along rows (axis=1): [1.41693396 2.78796651]

7. Mean of all elements in F: 0.3859


8. Cumulative sum of I along columns (first row):
[0.38867729 0.27134903 0.82873751 0.35675333 0.28093451]

9. Standard deviation of I: 0.3008

10. Index of minimum value in I (flattened): 12

11. C sorted along columns (first column): [0.02058449 0.21233911 0.30424224]

12. Unique elements in A (all unique as it is random): [0.15601864 0.37454012 0.59865848 0.73199394 0.95071431]

13. G flattened (first 4 values): [0.25877998 0.66252228 0.31171108 0.52006802]



In [ ]:
#5.2 Perform operation on two arrays of same size (eg. multiplication, etc.)

print("\n\n--- 2. OPERATIONS ON TWO ARRAYS OF SAME SIZE (6 Functions) ---")

# 14. Element-wise Addition
sum_A_B = A + B
print(f"\n14. A + B (Element-wise Addition, first 3 values):\n{sum_A_B[:3]}\n")

# 15. Element-wise Multiplication
mult_C_D = C * D
print(f"15. C * D (Element-wise Multiplication, first element): {mult_C_D[0, 0]:.4f}\n")

# 16. np.maximum (Universal Function)
max_E_F = np.maximum(E, F)
print(f"\n16. np.maximum(E, F) (First row):\n{max_E_F[0]}\n")

# 17. np.subtract (Universal Function)
sub_H_G = np.subtract(H, G)
print(f"17. H - G (Element-wise Subtraction, first 2 rows):\n{sub_H_G[:2]}\n")

# 18. np.power (Universal Function)
pow_I_J = np.power(I, J)
print(f"\n18. I to the power of J (First element): {pow_I_J[0, 0]:.4f}\n")

# 19. np.greater (Comparison)
greater_I_J = np.greater(I, J)
print(f"19. np.greater(I, J) (Check if I > J - first row):\n{greater_I_J[0]}\n")



--- 2. OPERATIONS ON TWO ARRAYS OF SAME SIZE (6 Functions) ---

14. A + B (Element-wise Addition, first 3 values):
[0.53053464 1.00879792 1.59817009]

15. C * D (Element-wise Multiplication, first element): 0.0060


16. np.maximum(E, F) (First row):
[0.59241457 0.09767211 0.68423303 0.44015249]

17. H - G (Element-wise Subtraction, first 2 rows):
[[0.68071896 0.23230507]
 [0.2861889  0.40180621]]


18. I to the power of J (First element): 0.7354

19. np.greater(I, J) (Check if I > J - first row):
[ True False  True False False]



In [ ]:
#5.3 Perform operation on two arrays of different size (eg. dot product between array of size 2x4 and 4x2

print("\n\n--- 3. OPERATIONS ON DIFFERENT SIZE ARRAYS / MATRIX OPS (4 Functions) ---")

# 20. Matrix Multiplication (E @ G) -> (2x4) @ (4x2) = 2x2
matrix_mult_1 = E @ G
print(f"\n20. E @ G (Matrix multiplication, Result 2x2):\n{matrix_mult_1}\n")

# 21. Matrix Multiplication (np.dot(G, E)) -> (4x2) @ (2x4) = 4x4
matrix_mult_2 = np.dot(G, E)
print(f"\n21. np.dot(G, E) (Matrix multiplication, Top-left 2x2):\n{matrix_mult_2[:2, :2]}\n")

# 22. np.dot (Dot product of two 1D vectors)
dot_A_B = np.dot(A, B)
print(f"\n22. Dot product of A and B (Scalar result): {dot_A_B:.4f}\n")

# 23. np.linalg.det (Linear Algebra Function)
det_J = np.linalg.det(J)
print(f"23. Determinant of J (np.linalg.det(J)): {det_J:.4f}\n")



--- 3. OPERATIONS ON DIFFERENT SIZE ARRAYS / MATRIX OPS (4 Functions) ---

20. E @ G (Matrix multiplication, Result 2x2):
[[0.66527272 0.66113145]
 [1.62434278 1.34169986]]


21. np.dot(G, E) (Matrix multiplication, Top-left 2x2):
[[0.19640316 0.64067825]
 [0.21849344 0.50796413]]


22. Dot product of A and B (Scalar result): 1.2180

23. Determinant of J (np.linalg.det(J)): 0.0017

